{% set version = "2.5.0" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: 81eb00ea8157944b160156e22ba7bd2065b42144ae14138aa5a56fae22fefe8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - libpysal
    - pandas >1.4
    - scikit-learn >=1.0
    - scipy >=1.9

test:
  imports:
    - esda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Exploratory Spatial Data Analysis

extra:
  recipe-maintainers:
    - ocefpaf
