{% set version = "2.4.1" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: 308b43cdc2f7af9b01c4a71fb1869092d48bcdf953e99dba8fc8239745779f1e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.4
    - pip
  run:
    - python >3.4
    - libpysal
    - pandas
    - scikit-learn
    - scipy >=0.11

test:
  imports:
    - esda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Exploratory Spatial Data Analysis

extra:
  recipe-maintainers:
    - ocefpaf
