{% set version = "2.6.0" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: 95a3732bf222f93509dff72300dd2ae5687ffefacd7862e56ab44a27297d5274

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10
    - geopandas >=0.12
    - libpysal >=4.12
    - numpy >=1.24
    - pandas >1.5
    - scikit-learn >=1.2
    - scipy >=1.9
    - shapely >=2.0

test:
  imports:
    - esda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Exploratory Spatial Data Analysis

extra:
  recipe-maintainers:
    - knaaptime
    - martinfleis
    - jGaboardi
    - ocefpaf
